# To run these tests, simply execute `nimble test`.

import unittest

import nom


test "All tags":
  echo Node()
  #echo HTMLElement() # leave these private for now
  echo html()
  assert $html() == "<html></html>"
  echo html("hello world!")
  echo html("hello world!", "here's another line")
  echo body()
  echo html(body("Hello World!"))

  var document = html(body("Hello World!"))
  echo document

  echo html(body("Hello World!", id="page"))
  echo html(body(div("Hello World!"), id="page"))
  echo html(body(div(h1("Hello World!")), id="page"))
  echo html(body(div(h1("Hello World!", class="greeting")), id="page"))
  echo html(body(div(h1("Hello World!")), id="page", class="greeting"))
  echo body(h1("Hello World!"), class="greeting")
  echo h1(h1("Hello World!"), class="greeting")

  # div is a builtin binary operator so needs backticks when called or it errors
  echo `div`("Hello World!")
  #echo `div`(h1("Hello World!"), "test", class="greeting")
  #echo `div`("Hello")
  #echo `div`("Hello", class="greeting")

  # uppercase might be the solution... (test this on domonic too? for certain tags? and params?)
  echo Div("greeting", class="test")

  # TODO - consistency. make them all caps??
  #echo Html(Body(Div(H1("Hello World!")), id="page", class="greeting"))

  echo html(body(Div(h1("Hello World!")), id="page", class="greeting"))

  echo h1("test")
  echo h2("test")
  echo h3("test")
  echo h4("test")
  echo h5("test")
  echo script("test")
  echo style("test")
  echo p("test")
  echo i("test")
  echo b("test")
  echo a("test")
  echo ul("test")
  echo ol("test")
  echo li("test")
  echo strong("test")
  echo blockquote("test")
  echo table("test")
  echo tr("test")
  echo td("test")
  echo form("test")
  echo label("test")
  echo submit("test")
  echo title("test")
  echo noscript("test")
  echo section("test")
  echo nav("test")
  echo article("test")
  echo aside("test")
  echo hgroup("test")
  echo address("test")
  echo pre("test")
  echo dl("test")
  echo dt("test")
  echo dd("test")
  echo figure("test")
  echo figcaption("test")
  echo em("test")
  echo small("test")
  echo s("test")
  echo cite("test")
  echo q("test")
  echo dfn("test")
  echo abbr("test")
  echo code("test")
  #echo var("test")
  echo samp("test")
  echo kbd("test")
  echo sub("test")
  echo sup("test")
  echo u("test")
  echo mark("test")
  echo ruby("test")
  echo rt("test")
  echo rp("test")
  echo bdi("test")
  echo bdo("test")
  echo span("test")
  echo ins("test")
  echo iframe("test")
  echo video("test")
  echo audio("test")
  echo canvas("test")
  echo caption("test")
  echo colgroup("test")
  echo tbody("test")
  echo thead("test")
  echo tfoot("test")
  echo th("test")
  echo fieldset("test")
  echo legend("test")
  echo button("test")
  echo select("test")
  echo datalist("test")
  echo optgroup("test")
  echo option("test")
  echo textarea("test")
  echo output("test")
  echo progress("test")
  echo meter("test")
  echo details("test")
  echo summary("test")
  echo menu("test")
  echo menuitem("test")
  echo font("test")
  echo header("test")
  echo footer("test")
  echo data("test")
  echo base("test")
  echo link("test")
  echo meta("test")
  echo hr("test")
  echo br("test")
  echo wbr("test")
  echo img("test")
  echo param("test")
  echo source("test")
  echo track("test")
  echo area("test")
  echo col("test")
  echo input("test")
  echo keygen("test")
  echo command("test")
  echo main("test")
  echo applet("test")
  echo basefont("test")
  echo center("test")
  echo embed("test")
  echo isindex("test")
  echo listing("test")
  echo plaintext("test")
  echo s("test")
  echo picture("test")
  echo dialog("test")



  #Node()
  #Node 1 23, 3 
  #echo html()
  #echo body()
  #echo html(content:body())
  #echo html(content="test", attributes="test")
  #echo html(body("test"))